Repository RobbieTheWagner/ember-meta, pull requests merged in 2020-07, with the labels that each got.

#15 move emberMetaConfig into the service so it can be overloaded
  addon/services/head-data.js
Labels: enhancement

#16 ember-cli-head 1.0.0
  package.json
  yarn.lock
Labels: breaking

#17 Convert service to native class
  addon/services/head-data.js
Labels: internal
